"""
Model for QKD simulation based on BB84 protocol, in the most essential form.
Class designed for the environment.py to inherit from. The physical engine in the advanced version 
will inherit Alice's generation without operating modifications on it.

Main actions of the current engine:
- Alice generation=> bit and bias basis generation
- channel simulation=> Eve doing Evel things
- sifting=> basis reconciliation, wrong bits get discarded

A static dataset can be generated for physicalengine type objects, with a dedicated function 
(the last cited below).
"""

#from turtle import pd
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import random
import os

#initializing a random seed (with a specific value) for reproducibility was proved to be 
# causing issues: REMOVED
#np.random.seed(42)
np.random.default_rng(random.seed())

class QKDEngine:
    #def __init__(self, bits, bias, channel_loss, bit_flip, p_eve): #initial version
    def __init__(self, bits, bias, L, bit_flip, p_eve):
        self.bts= bits #information Alice wants to send to Bob (len in bits)
        self.bias=bias #probability of choosing a Z basis over an X base (0.5=50% Z, 50% X)
        self.L=L #channel lenght (km) or distance covered by channel
        self.chloss=1-10**((-self.L*0.2)/10) #computation of the LOSS based on L 
        #attenuation coefficient: alpha=0.2dB/km
        #NB model MUST remain dummy: despite kniwing the L it does not use it to adapt bias (FIXED@0.5)
        self.bifl=bit_flip #bit flip probability (noise in the system, hardware error)
        self.p_eve=p_eve #probability of Eve intercepting the channel (external attacks)
    
    def generate_Alice(self):
        """
        This function generates Alice's bits and bases RANDOMLY (based on FIXED bias).
        Returns:
            - Abits: array of bits generated by Alice;
            - crypted_bases: array of bases generated by Alice (0=Z, 1=X).
        NOTEforUser: in case specific bits were meant to be sent, Alice could feed the channel 
        that sequence without the need ofgenerating and encoiding them.
        """
        Abits=np.random.randint(0, 2, self.bts) #information bits Alice RANDOMLY GENERATES 
        crypted_bases=np.zeros(self.bts) #empty array for Alice's bases (0=Z, 1=X)
        mask=np.random.rand(self.bts) #generazione random per scelta A basi
        pz=self.bias 
        #from law of tot prob: px=1-pz, given pz
        for i in range(self.bts):
            if mask[i]<pz: #choice base Z
                crypted_bases[i]=0
            else:
                crypted_bases[i]=1 #choice: base X
        return Abits, crypted_bases
    
    def channel_simulation(self, crypted_bases, Abits):
        """
        The function defined simulates channel dynamics (keeping the model dummy).
        It simulates:
            - channel losses (based on self.chloss);
            - Eve attacks (upon defining self.p_eve);
            - bit flip (rooted on self.bifl).
        Returns:
            - outputAbits: array of bits that survived the channel;
            - outputcrypted_bases: array of bases (bits coded) that survived the channel.
        """

        N=int(self.bts)
        survived_mask=np.zeros(N) #0=died, 1=survived

        # channel losses:
        loss_mask=np.random.rand(N)
        survived_mask[loss_mask>self.chloss]=1 #if the random number exceeds the loss one, it survives
        Abits=Abits[survived_mask==1] #Alice bits survived to the channel
        crypted_bases=crypted_bases[survived_mask==1] #crypting bases surviving channel up to now

        nl=len(Abits) #dimension of survived arrays

        # Eve attacks: 
        #ORIGINAL: #eve_mask = np.random.rand(nl) < self.p_eve
        eve_selector=np.random.rand(nl) #random generation for choosinhh if Eve attacks or not
        eve_mask=np.zeros(nl) #initial empty array for Eve's mask
        eve_mask[eve_selector<self.p_eve]=1 #based on peve, E decides whetger to attack
        eve_bases=np.zeros(nl) #empt array for EVe's bases
        for i in range(nl):
            if eve_mask[i]==1: #Eve attacks
                eve_bases[i]=np.random.randint(0,2) #Eve chooses random base
                if eve_bases[i]==crypted_bases[i]: #(un)luckily (for us), she chose the right one
                    pass #no change in the bit
                else:
                    Abits[i]=np.random.randint(0,2) #bit that were 0 become 1 and vice versa, with 50% probability, Eve introduced error
        
        # bit flip:
        flip_mask=np.random.rand(nl)
        Abits[flip_mask<self.bifl]=1-Abits[flip_mask<self.bifl] #if numb is <, bit gets inverted (0->1, 1->0) w.p. self.bifl
        
        outputAbits=Abits
        outputcrypted_bases=crypted_bases
        return outputAbits, outputcrypted_bases
    
    def generate_Bob(self, outputAbits, outputcrypted_bases):
        """
        Bob's generation pipeline: generation of B bases, generation of B bits with noise and channel loss.
        Returns:
            - Bbits: array of bits generated by Bob;
            - Bcrypted_bases: array of bases generated by Bob (memo: 0=Z, 1=X).
        NOTEforUser: QBER in this version gets induced with distance (losses increase aW), through
            formulation based on ASSUMPTION: 2% internal noise of the system + effect biund to chloss
        """
        nl=len(outputAbits)
        bmask=np.random.rand(nl) #random generation for choosing Bob's bases
        Bcrypted_bases=np.zeros(nl) #empty array initialization for Bob's encrypted bits
        pz=self.bias #probability of choosing base Z, given LoTP
        #Bcrypted_bases[bmask<pz]=0 #choice of base Z
        Bcrypted_bases[bmask>=pz]=1 #choice of base X
        match=np.zeros(nl) #mask for bits where Alice and Bob's bases coincide
        match[Bcrypted_bases==outputcrypted_bases]=1 #matching bases: bit is 1 (otherwise 0)
        n_mismatch=np.sum(match==0) #tot of bits for which the bases do not coincide
        Bbits=np.zeros(nl) #initialization of empty array for Bob's bits
        error_probability=0.02+0.1*self.chloss #QBER induced articicially
        error_mask=np.random.rand(nl)<error_probability
        corrupted_bits=np.copy(outputAbits) #Bob receives bits
        corrupted_bits[error_mask]=1-corrupted_bits[error_mask] #if error, bit is flipped (0->1 or 1->0)
        Bbits[match == 1] = corrupted_bits[match == 1] #Bob gets assigned bits (corrupted by noise) where bases match
        Bbits[match == 0] = np.random.randint(0, 2, n_mismatch) #if bases dont mathc, B measures randomly 
        return Bbits, Bcrypted_bases
    
    def sifting(self, outputAbits, outputcrypted_bases, Bbits, Bcrypted_bases):
        """
        This function represents the sifting step: Alice and Bob actually compare their bases
        and discard those mismatched.
        Returns:
            - Asifted_key: array of bits that survived the sifting (Alice's);
            - Bsifted_key: array of bits that survived the sifting (Bob's).
        """
        nl=len(outputAbits) #survived bits lenght
        matching_mask=np.zeros(nl)
        matching_mask[outputcrypted_bases==Bcrypted_bases]=1 #mask for bits where Alice and Bob's bases coincide
        Asifted_key=outputAbits[matching_mask==1] #sifted key, only bits where bases coincide
        Bsifted_key=Bbits[matching_mask==1] #sifted key of Bob, only bits where bases coincide
        return Asifted_key, Bsifted_key
    
    def calculate_metrics(self, Asifted_key, Bsifted_key):
        """
        The function above here calculates the metrics associated with the sifted key computation.
        Returns:
            - qber: Quantum Bit Error Rate;
            - key_length: length of the sifted key.
        """
        tot_outbits=len(Asifted_key) #total number of sifted bits
        if tot_outbits==0:
            return 0,0 #QBER=0, len(key)=0
        else:
            tot_errors=np.sum(Asifted_key!=Bsifted_key) #total number of errors, bits where Alice and Bob differ
            qber=tot_errors/tot_outbits #QBER, ratio between errors and total bits
            return qber, tot_outbits #returns QBER and length of the sifted key
    
    #def generate_static_dataset(self, n_samples):
    def generate_static_dataset(self, n_samples_per_distance):
        """
        Generation, population and saving of static dataset for dummy model.
        Dataset saved in csv format in local path.
        Returns:
            - finale_df: DataFrame containing the generated dataset.
        """
        all_framess=[]
        L=np.linspace(0, 150, 16) #[0, 10, 20, ..., 140, 150] distances in km
        # out_dir="C:/Users/rorag/VS_Cpp/thesis proj/dummy_model"
        # file_name="dataset_dummy_fortraintest.csv"
        # full_path=os.path.join(out_dir, file_name)
        current_script_dir=os.path.dirname(os.path.abspath(__file__))
        out_dir=os.path.join(current_script_dir, "dummy_model") #creation of folder dummy model
        file_name="dataset_dummy_fortraintest.csv"
        full_path=os.path.join(out_dir, file_name)
        if not os.path.exists(out_dir): #in case folder does not exist allready
            os.makedirs(out_dir) #create it
            print(f"Directory '{out_dir}' created.")
        for l in L:
            self.L=l
            self.chloss=1-10**((-self.L*0.2)/10) #calcolo della perdita in base alla distanza L 
            print(f"Generating dataset for distance {l} km (Loss={self.chloss:.4f})...")
            for i in range(n_samples_per_distance):
            #NextEngine: current_bias=np.random.uniform(0.1, 0.9)
                current_bias=0.5 #BIAS FIXED for BASELINE
                #current_loss=np.random.uniform(0.0, 0.5) #variation for less dummy model
                self.bias=current_bias
                A_bits, A_bases=self.generate_Alice()
                out_bits, out_bases=self.channel_simulation(A_bases, A_bits)
                B_bits, B_bases=self.generate_Bob(out_bits, out_bases)
                A_sifted_key, B_sifted_key=self.sifting(out_bits, out_bases, B_bits, B_bases)
                qber, key_lenght=self.calculate_metrics(A_sifted_key, B_sifted_key)
                # dataset:
                df_simulation_def={
                    'sim_id': i, #simulation id
                    'bias': self.bias, 
                    'channel loss': self.chloss,
                    'QBER': qber,
                    'key_length': key_lenght,
                    'distance': self.L,
                    'sift_match_rate': len(A_sifted_key)/len(out_bits) if len(out_bits)>0 else 0,
                    #number of bits preserved in the key wrt the ones that survived the channel
                    'sift_match': (out_bases==B_bases).mean() if len(out_bits)>0 else 0
                    #aka: Alice and Bob s agreement rate, should be about 0.5
                }
                all_framess.append(df_simulation_def)
                if (i + 1) % 100==0: #prints progress every 100 sessions
                    print(f"Completed {i + 1}/{n_samples_per_distance} sessions...")
        finale_df = pd.DataFrame(all_framess)

        # if not os.path.exists(out_dir):
            # os.makedirs(out_dir)
            # print(f"Directory '{out_dir}' created.")

        finale_df.to_csv(full_path, index=False)
        print(f"Dataset saved successfully in: {full_path}")
        print(f"Total rows: {len(finale_df)}")
        return finale_df